SEGMENTATION_SPATIALR_PARAM = 20;
SEGMENTATION_RANGER_PARAM = 15;
SEGMENTATION_MINSIZE_PARAM = 50;

TEXTURE_EXTRACTION_XRAD_PARAMETER = 2;
TEXTURE_EXTRACTION_YRAD_PARAMETER = 2;
TEXTURE_EXTRACTION_NBBIN_PARAM = 8;
